name: CI

on:
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - '**.md'
      - '**.pdf'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Test
        run: go test ./... -coverprofile=coverage.out
