name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: dependabot-auto-merge
    runs-on: ubuntu-latest

    if: |
      github.actor == 'dependabot[bot]' &&
      (github.event.pull_request.base.ref == 'development' ||
      github.event.pull_request.base.ref == 'main')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - name: Auto approve
        run: gh pr review --approve "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge (squash)
        run: gh pr merge --squash --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
