name: Security

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.pdf'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - '**.md'
      - '**.pdf'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...